name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: slidev build --base chinese-kitchen-slides
      - uses: actions/upload-artifact@v3
        with:
          name: slidev-exported.pdf
          path: dist/slidev-exported.pdf

